version: '3.4'

services:
  syncmailhub-api:
    image: ${DOCKER_REGISTRY-}api
    container_name: syncmailhub-api
    build:
      context: .
      dockerfile: src/App/Dockerfile
    depends_on:
      - syncmailhub-db

  syncmailhub-app:
    image: ${DOCKER_REGISTRY-}app
    container_name: syncmailhub-app
    build:
      context: src/web-app
      dockerfile: Dockerfile
    depends_on:
      - syncmailhub-api

  syncmailhub-db:
    image: postgres:latest
    container_name: syncmailhub-db

  syncmailhub-db-management:
    image: dpage/pgadmin4:latest
    container_name: syncmailhub-db_management
    depends_on:
      - syncmailhub-db

  syncmailhub-seq:
    image: datalust/seq:latest
    container_name: syncmailhub-seq

  syncmailhub-redis:
    image: redis:latest
    container_name: syncmailhub-redis

  syncmailhub-redis-insight:
    image: redis/redisinsight:latest
    container_name: syncmailhub-redis-insight
